### ISSUE TITLE
test

### ISSUE THREAD

**Issue by TobiasWeis** [TobiasWeis/robotcontrol-javascript#1]
test

**Comment by bancroftd** [comment]
Hi Tobias
I like the work you have done. I would like to make a special RC car. What I am looking for is stearing(servo), motor control(simple PWM), Wheel lift (servo push button up and press again to lower) and some leds lights on and off. Now from your code I can use the joystick for stearing, any way a motor can be used for the vertical part for the joystick? Also lastly the start and rest posistion of the servos, can they be configure to be center?

Thanks your work is appreciated
