### ISSUE TITLE
Question for running 2 DC motos (with gpiozero library used too)

### ISSUE THREAD

**Issue by greatmarauder** [TobiasWeis/robotcontrol-javascript#3]
With regards to the previous issue as I think mine is a bit similar, I'm trying to get the joystick on the webpage to work on my pi car running on 2 dc motors. How do I get the X and Y values of the joystick into Python? I want the values so that I can change the  motor speed using gpiozero library (eg when I push the joystick forward, giving X=0, Y=1 so that the car moves forward, I want something like "robot.value(Y,Y)" to control the speed of left and right motors respectively). This has to be done in the "def run(self)" section right? I have my car wired up to the pi and a L293D module to control the motors.

**Comment by TobiasWeis** [comment]
In the robot-folder, create a class for your DC-Motor - have a look at the Servo-class, it'll be nearly the same, except you need to change the mapping so the PWM fits your motor.
In the run()-function you can get the inputs from the queue using 
inp = queue.get_nowait(). 

You can get the values of the left joystick with:
inp["right"][0] # x-axis
inp["right"][1] # y-axis
